---
##########################
## Hadolint config file ##
##########################
ignored:
  - DL3007
  - DL3007
  - DL3013
  - DL3021
  - DL3004
  - SC3016
  - DL3020
  - DL3025
  - DL4001
  - DL4006